### ISSUE TITLE
Add an homebrew installation method

### ISSUE THREAD

**Issue by remyleone** [rusq/slackdump#236] opened 2023-09-26 09:44 UTC
**Is your feature request related to a problem? Please describe.**

I would like to install and keep updated a slackdump installation using homebrew

**Describe the solution you'd like**

brew install slackdump

**Describe alternatives you've considered**

Manual installation

**Comment by rusq** [comment] 2023-09-26 09:46
Duplicate of #173

**Closed** 2023-09-26 09:46 UTC
Labels: duplicate
