### ISSUE TITLE
Resume export after interruption

### ISSUE THREAD

**Issue by whatupjeff** [rusq/slackdump#313] opened 2024-08-21 09:40 UTC
While performing a large export, my connection may time out and require me to start over. Is it possible to continue exporting where it left off?

**Comment by rusq** [comment] 2024-08-22 07:54
Hey, currently not implemented, but planned, no ETA, but you can check this solution: https://github.com/rusq/slackdump/issues/214#issuecomment-1706294640

This is duplicate of #214

**Closed by rusq** 2024-08-22 07:54 UTC
