### ISSUE TITLE
JSON marshalling error during export

### ISSUE THREAD

**Issue by zarkdav** [rusq/slackdump#87] opened 2022-06-30 07:41 UTC
**Describe the bug**
Using v2.0.0 I get the following error in the middle of the export of my workspace:
channels: error: failed dumping "" (DHRCM1N81): json: cannot unmarshal number into Go struct field Message.messages.blocks of type string

The channel ID is the one from the outlook_calendar. I still get the error after disconnecting from Slack. How can I exclude this channel to finish the export successfully?

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by rusq** [comment] 2022-06-30 08:14
Thanks for your report, of course.

Also, I'm keen to learn more about the outlook_calendar to do a proper fix for that - not just exclude -  is this some custom integration or publicly available app?

**Comment by zarkdav** [comment] 2022-06-30 08:28
Indeed, it's a publicly available app:
https://slack.com/app-pages/outlook-calendar

Let me know if I can help get further debug information.

**Comment by rusq** [comment] 2022-07-02 10:19
Fixed in https://github.com/rusq/slackdump/pull/88

Once merged, I'll make a v2.0.1 release, that will include this fix.  You'll be able to exclude the problematic channel by specifying it's ID or URL on the command line, like so:

```shell
slackdump.exe -export my_export.zip ^DHRCM1N81
```
(note the "^" prefix, it tells slackdump to exclude the channel)

I've also introduced "@" prefix, so one can prepare the list in a file, and include it like this:
```shell
slackdump.exe -export my_export.zip @mylist.txt
```
Most likely I'll merge tomorrow, need to doublecheck it to ensure it works.

I also installed the Outlook Calendar in my test environment, but could not reproduce the error.  I suspect that it has sent you some message, which I wasn't able to get from it.

Can you try exporting that channel using the Standard export mode, please?  And see if it crashes and burns:
```
slackdump.exe DHRCM1N81
```
If successful - it will generate the DHRCM1N81.json file.  Could you please let me know if that works?

**Comment by zarkdav** [comment] 2022-07-02 15:53
Hi,

First of all thank you for the patch, looks like it will work great! I agree, it must be the specific content from the bot that is generating the error.

On your last question, with 2.0.0 I get very limited content on the generated json file, but at the same time I disconnected the app and set the channel to purge after 1 day, so that might be the reason:
`{
  "name": "",
  "messages": null,
  "channel_id": "DHRCM1N81"
}`

**Comment by rusq** [comment] 2022-07-03 02:59
No problem :)

Thank you for checking, it looks like an empty export indeeed, whatever was causing the issue is gone.

It's a good thing that you raised this issue - I should have implemented the channel inclusion/exclusion from the start. It also allowed me to revisit the way that the export was done, something I've been putting away for a long time.

Here's the windows build: [slackdump-v2.0.1-windows-amd64.zip](https://github.com/rusq/slackdump/releases/download/v2.0.1/slackdump-v2.0.1-windows-amd64.zip)

Please let me know if you encounter any issues with this.

**Closed by rusq** 2022-07-03 02:59 UTC
