### ISSUE TITLE
When using export-type mattermost program downloads files anyway

### ISSUE THREAD

**Issue by ShalyapinSNET** [rusq/slackdump#227] opened 2023-07-10 11:12 UTC
**Describe the bug**
I want to export channel without shared files. I use command without '-download' flag:
`slackdump -export my-workspace.zip -export-type mattermost CXXXXXX`

But slackdump downloads all files from channel anyway. 
Is there a way to do import without content?

**Desktop (please complete the following information):**
 - Version: Slackdump 2.4.0 (commit: 4e9bb6fd2af4d773ffb99d1ba77abf5506ec89f0) built on: 2023-05-20T00:00:48Z
 - OS: Ubuntu 18.04.6 LTS

**Comment by rusq** [comment] 2023-07-10 11:43
Hey @ShalyapinSNET, the "mattermost" implies that you want to download files, because mattermost only affects how the files are stored.

Behind the scenes there are three modes:
- nodownload
- standard
- mattermost

they are mutually exclusive, so when you specify that you want "mattermost" it enables the files download and overrides `-download` flag.

In your case, just run it like this:
```
slackdump -export my-workspace.zip CXXXXXX
```
and everything will be chiki briki.

Sorry, I can confirm that's bad UX, it will be fixed in v3.

**Closed** 2023-07-11 07:26 UTC
