### ISSUE TITLE
Export max size limit? "Bad magic number for file header"

### ISSUE THREAD

**Issue by csaket** [rusq/slackdump#90] opened 2022-07-18 19:37 UTC
**Describe the bug**
I am exporting a bunch of channels, DMs etc. The export finishes without errors.
When I try to open the zip file created, I get this error.
```
Windows cannot open the folder.
The Compressed (zipped) Folder 'C:\Data\SlackDump\my-workspace.zip' is invalid.
```
Other software gives the error in the title.

One thing I have noticed is that the zip is roughly 1 GB in size in size, hence the question on size limits.

I have not had the issue with exporting a couple of channels and DMs where the size was much smaller.

**To Reproduce**
1. ` .\slackdump.exe -export my-workspace.zip -download -user-cache-age 96h0m0s -user-cache-file u.cache G02*** D02*** C02*** ...`

**Expected behavior**
Usable export file.
Using the suggested slack-export-viewer works with smaller size archive.

**Output**
The output reports completion but curiously logs an additional save afterwards.
```
2022/07/18 14:11:27   thread fetch complete, total: 6
2022/07/18 14:11:27 messages request #    3, fetched:   31 (threads: 14, files: 8), total:      431 (speed:   2.22/sec, avg:   2.54/sec)
2022/07/18 14:11:27 messages fetch complete, total: 431
2022/07/18 14:11:33 completed, time taken: 26m30.7357232s
2022/07/18 14:11:33 file "F02***-image.png" saved to abcd\attachments: 24999 bytes written
```

**Desktop (please complete the following information):**
 - OS: Windows 11 
22H2 (OS Build 22622.290)

Running 
```
PS C:\Data\SlackDump> .\slackdump.exe -V
Slackdump v2.0.1 Copyright (c) 2018-2022 rusq (build: 1c46ed8)

v2.0.1
```

Ran a smaller export with the `trace` option.

```
2022/07/18 14:42:57   thread fetch complete, total: 2
2022/07/18 14:42:58   thread request #    1, fetched:    4, total:        4, process results:  (speed:  10.67/sec, avg:  10.67/sec)
2022/07/18 14:42:58   thread fetch complete, total: 4
2022/07/18 14:42:58 messages request #    1, fetched:   43 (threads: 10, files: 14), total:       43 (speed:  11.80/sec, avg:  11.80/sec)
2022/07/18 14:42:58 messages fetch complete, total: 43
2022/07/18 14:43:04 completed, time taken: 24.2782739s
2022/07/18 14:43:04 error saving "F0***K-Access for abcd.docx" to cba\attachments: write my-workspace2.zip: file already closed
2022/07/18 14:43:04 error saving "F0***W-image.png" to cba\attachments: write my-workspace2.zip: file already closed
2022/07/18 14:43:04 error saving "F0***7-image.png" to cba\attachments: write my-workspace2.zip: file already closed
2022/07/18 14:43:04 error saving "F0***Y-image.png" to cba\attachments: context canceled
2022/07/18 14:43:04 error saving "F0***A-image.png" to cba\attachments: write my-workspace2.zip: file already closed
2022/07/18 14:43:04 error saving "F0***9-Untitled.js" to cba\attachments: context canceled
PS C:\Data\SlackDump> dir
```

**Comment by rusq** [comment] 2022-07-19 01:52
Hey @csaket thanks for reporting this.

That's interesting, the last chunk of output is really helpful - looks like there's a concurrency issue - the main thread completes the export and closes the handles, and the download workers still try to update the file, which has already been closed by then.  I'll have a look.

**Comment by rusq** [comment] 2022-07-19 10:11
@csaket This should be fixed, could you please retry the "a smaller export with the trace option" with [v2.0.2](https://github.com/rusq/slackdump/releases/download/v2.0.2/slackdump-v2.0.2-windows-amd64.zip)? 

Trace option is not strictly necessary - it is mostly used for debugging (generates a `trace.out` file) and does not add to the logging output.

More verbose logging can be achieved by running with `-v` flag:  for instance `slackdump.exe -v -export my-workspace.zip -download -user-cache-age 96h0m0s -user-cache-file u.cache G02*** D02*** C02*** ...`

**Comment by csaket** [comment] 2022-07-19 17:11
Hi, the smaller export worked. No errors while running dump and I was able to use the viewer and could see the messages. The embedded images though do not show up.
I ran a larger export which completed and is ~312MB and it did not show any error messages even with a `-v` 

error I get when trying the viewer:
`zlib.error: Error -3 while decompressing data: invalid stored block lengths`

Trying with all the channels/etc I wanted, it errors out:

```
2022/07/19 12:05:07 downloader.go:175: saving "F***-image.png" to attachments, size: 111956
2022/07/19 12:05:07 export.go:233: submitted for download: image.png
2022/07/19 12:05:07 export.go:233: submitted for download: image.png
2022/07/19 12:05:07 export.go:233: submitted for download: image.png
2022/07/19 12:05:07 export.go:233: submitted for download: image.png
2022/07/19 12:05:07 export.go:233: submitted for download: image.png
2022/07/19 12:05:07 messages.go:144: messages request #    2, fetched:  200 (threads: 0, files: 5), total:      400 (speed: 175.18/sec, avg: 234.50/sec)
2022/07/19 12:05:07 downloader.go:181: file "F***-image.png" saved to attachments: 47634 bytes written
2022/07/19 12:05:07 downloader.go:175: saving "F***-image.png" to attachments, size: 186328
2022/07/19 12:05:07 downloader.go:181: file "F***-image.png" saved to attachments: 77832 bytes written
2022/07/19 12:05:07 downloader.go:175: saving "F***-image.png" to attachments, size: 126414
2022/07/19 12:05:07 downloader.go:181: file "F***-image.png" saved to attachments: 111956 bytes written
2022/07/19 12:05:07 downloader.go:175: saving "F***-image.png" to attachments, size: 53204
2022/07/19 12:05:07 downloader.go:181: file "F***-image.png" saved to attachments: 186328 bytes written
2022/07/19 12:05:07 downloader.go:175: saving "F***-image.png" to attachments, size: 40896
2022/07/19 12:05:07 thread.go:149:   thread request #    1, fetched:    2, total:        2, process results:  (speed:  12.96/sec, avg:  12.96/sec)
2022/07/19 12:05:07 thread.go:157:   thread fetch complete, total: 2
2022/07/19 12:05:07 messages.go:144: messages request #    3, fetched:   59 (threads: 1, files: 0), total:      459 (speed: 165.29/sec, avg: 222.52/sec)
2022/07/19 12:05:07 messages.go:151: messages fetch complete, total: 459
2022/07/19 12:05:08 downloader.go:181: file "F***-csv.zip" saved to attachments: 4712660 bytes written
2022/07/19 12:05:08 downloader.go:175: saving "F***-image.png" to attachments, size: 32095
2022/07/19 12:05:08 downloader.go:181: file "F***-image.png" saved to attachments: 126414 bytes written
2022/07/19 12:05:08 downloader.go:175: saving "F***-image.png" to attachments, size: 111086
2022/07/19 12:05:08 downloader.go:181: file "F***-image.png" saved to attachments: 53204 bytes written
2022/07/19 12:05:08 downloader.go:175: saving "F***-image.png" to attachments, size: 40330
2022/07/19 12:05:08 downloader.go:260: chan closed
2022/07/19 12:05:08 downloader.go:181: file "F***-image.png" saved to attachments: 40896 bytes written
2022/07/19 12:05:08 downloader.go:175: saving "F***-image.png" to attachments, size: 272451
2022/07/19 12:05:08 downloader.go:181: file "F***-image.png" saved to attachments: 32095 bytes written
2022/07/19 12:05:08 downloader.go:175: saving "F***-image.png" to attachments, size: 37167
2022/07/19 12:05:08 downloader.go:181: file "F***-image.png" saved to attachments: 40330 bytes written
2022/07/19 12:05:08 downloader.go:175: saving "F***-image.png" to attachments, size: 33912
2022/07/19 12:05:08 downloader.go:181: file "F***-image.png" saved to attachments: 111086 bytes written
2022/07/19 12:05:08 downloader.go:175: saving "F***-image.png" to attachments, size: 5338
2022/07/19 12:05:08 downloader.go:181: file "F***-image.png" saved to attachments: 272451 bytes written
2022/07/19 12:05:08 downloader.go:175: saving "F***-image.png" to attachments, size: 15280
2022/07/19 12:05:08 downloader.go:181: file "F***-image.png" saved to attachments: 5338 bytes written
2022/07/19 12:05:08 downloader.go:157: download worker 1 terminated
2022/07/19 12:05:08 downloader.go:181: file "F***-image.png" saved to attachments: 15280 bytes written
2022/07/19 12:05:08 downloader.go:157: download worker 0 terminated
2022/07/19 12:05:08 downloader.go:181: file "F***-image.png" saved to attachments: 37167 bytes written
2022/07/19 12:05:08 downloader.go:175: saving "F***-image.png" to attachments, size: 6060
2022/07/19 12:05:08 downloader.go:181: file "F***-image.png" saved to attachments: 33912 bytes written
2022/07/19 12:05:08 downloader.go:157: download worker 2 terminated
2022/07/19 12:05:08 downloader.go:181: file "F***-image.png" saved to attachments: 6060 bytes written
2022/07/19 12:05:08 downloader.go:157: download worker 3 terminated
2022/07/19 12:05:08 downloader.go:262: wait complete
2022/07/19 12:05:08 application error: export error: serialize: failed to encode: zip: write to closed file
```

**Comment by rusq** [comment] 2022-07-19 20:36
Hey @csaket, thank you for checking.  I gotta ask - would you be willing to share a trace file for the failing session (my private dropbox link: https://www.dropbox.com/request/eEK5YK1srbvXPyBmnvys)?  I can see that for some reason it closes the file before it - trace file would give me the better understanding when that happens.

**Disclosure**:
- The trace file WILL contain the slack workspace name.
- It will NOT contain any secrets, such as your token or cookies.
- It will NOT be used for any other purpose other than diagnosing the issue.
- It WILL be deleted once I'm done diagnostics.

It's ok if you don't, it just makes it a bit harder.

**Comment by rusq** [comment] 2022-07-19 20:43
Speaking of embedded images,  I investigated on this some time in the past.  The reason they work with original slack exports is:
- Slack does not save the files into the export archive, but generates a special `xoxe` token and adds them to each and every file link within the export archive, while files retained on the slack server.  The link looks like "https://slack.com/..../file.jpg?xoxe=...export token here...", and everyone having this link with xoxe token can preview it.

The reason they don't work in Slackdump exports is:
- Slackdump saves the images in the archive, though it updates the links, slack-export-viewer can't access them on this links due to the implementation of the path - it does not expose the files of the subdirectories.

I haven't came up with a good solution for this yet.

**Comment by rusq** [comment] 2022-07-20 12:08
@csaket I should have mentioned this in the beginning, to **get the job done** in this case, it is not necessary to use "zip" file for export, you can run it without ".zip" suffix, and it will save in the directory of your choice, i.e. to save the data to "`some_dir`", start it like this.  It won't be affected by this issue:
```
slackdump.exe -export some_dir ...
```

I wasn't able to reproduce the issue locally, but that's most likely because my test instance has too few entries.  I would be grateful if you could continue working with me on this, if you have time.

**Comment by rusq** [comment] 2022-07-21 11:06
@csaket No worries, and thanks.

I was able to find bigger workspace, but so far I wasn't able to reproduce the issue with the latest master build, tried locally and in windows 8 VM.

Would you be able to run again the problematic export using the attached version? (compiled from latest master for win64
[slackdump-master-win64.zip](https://github.com/rusq/slackdump/files/9158757/slackdump-master-win64.zip)
)

**Comment by rusq** [comment] 2022-07-21 12:07
Practically, it panics on 2.3GB archive, see: https://github.com/rusq/slackdump/issues/93

**Comment by csaket** [comment] 2022-07-22 20:03
> @csaket No worries, and thanks.
> 
> I was able to find bigger workspace, but so far I wasn't able to reproduce the issue with the latest master build, tried locally and in windows 8 VM.
> 
> Would you be able to run again the problematic export using the attached version? (compiled from latest master for win64 [slackdump-master-win64.zip](https://github.com/rusq/slackdump/files/9158757/slackdump-master-win64.zip) )

I used this version to try and generate the export in zip format and it completed without any error.
The size though again stopped at 1 GB and the zip is unusable by windows/slack viewer.
7-zip can open it with errors and I see only 2 channels out of the many that I was trying it with.

HTH

**Comment by rusq** [comment] 2022-07-23 01:51
@csaket yesterday I was able to reproduce the issue locally on a larger slack workspace, and have found a race condition, described in the #94, the problem was with the way the files were created inside the ZIP archive by multiple goroutines (by default there's 4 goroutines that handle file downloads).  If more than one of those was calling "Create" to add a file to a ZIP archive at the same time, only one would succeed.  Problem was that the mutex should have been locked before the call to Create, and not after.

Maybe I'm being overly confident, but I made a v2.0.3 release that contains this fix: https://github.com/rusq/slackdump/releases/download/v2.0.3/slackdump-v2.0.3-windows-amd64.zip

I have successfully tested it with 2.3GB archive:
```
$ ./slackdump -f -export ~/wp/test3.zip -log testrun_full.log 
2022/07/23 10:17:08 main.go:179: trace will be written to "trace.out"
2022/07/23 10:17:08 slackdump.go:118: > checking user cache...
2022/07/23 10:17:08 app.go:61: export mode ON
2022/07/23 10:17:08 app.go:143: filesystem: <zip archive: /Users/rustam/wp/test3.zip>
2022/07/23 10:17:08 app.go:149: staring export to: <zip archive: /Users/rustam/wp/test3.zip>
<...>
2022/07/23 10:35:02 downloader.go:285: wait complete:  all files downloaded
2022/07/23 10:35:02 export.go:301: downloader stopped
2022/07/23 10:35:02 app.go:143: closing file system
2022/07/23 10:35:02 app.go:72: completed, time taken: 17m53.362280238s
```

Archive test:
```
$ ls -l ~/wp/test3.zip
2.3G 23 Jul 10:35 /Users/rustam/wp/test3.zip

$ unzip -t ~/wp/test3.zip
<... lots of text ...>
No errors detected in compressed data of /Users/rustam/wp/test3.zip.

$ 7z t ~/wp/test3.zip    

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,16 CPUs x64)

Scanning the drive for archives:
1 file, 2425607730 bytes (2314 MiB)

Testing archive: /Users/rustam/wp/test3.zip
--
Path = /Users/rustam/wp/test3.zip
Type = zip
Physical Size = 2425607730

Everything is Ok                                                               

Files: 3897
Size:       2515025147
Compressed: 2425607730
```

Unpack test on windows finished with no errors, it complained about some unusual file names of the attachments, i.e. emojis in filenames, but otherwise everything unpacked.:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/16064414/180585828-68830dff-7794-42ab-a899-4ee5a08dd9dd.png">

Could you try this one please and let me know if that fixes the issue for you?

**Comment by rusq** [comment] 2022-07-25 08:44
@csaket I'll close this for now, please reopen if it doesn't work for you.  Thank you for contribution, I appreciate your help with this!

**Closed by rusq** 2022-07-25 08:44 UTC
Labels: bug

**Comment by csaket** [comment] 2022-07-29 14:21
> @csaket yesterday I was able to reproduce the issue locally on a larger slack workspace, and have found a race condition, described in the #94, the problem was with the way the files were created inside the ZIP archive by multiple goroutines (by default there's 4 goroutines that handle file downloads). If more than one of those was calling "Create" to add a file to a ZIP archive at the same time, only one would succeed. Problem was that the mutex should have been locked before the call to Create, and not after.
> 
> Maybe I'm being overly confident, but I made a v2.0.3 release that contains this fix: https://github.com/rusq/slackdump/releases/download/v2.0.3/slackdump-v2.0.3-windows-amd64.zip
> 
> I have successfully tested it with 2.3GB archive:
> 
> ```
> $ ./slackdump -f -export ~/wp/test3.zip -log testrun_full.log 
> 2022/07/23 10:17:08 main.go:179: trace will be written to "trace.out"
> 2022/07/23 10:17:08 slackdump.go:118: > checking user cache...
> 2022/07/23 10:17:08 app.go:61: export mode ON
> 2022/07/23 10:17:08 app.go:143: filesystem: <zip archive: /Users/rustam/wp/test3.zip>
> 2022/07/23 10:17:08 app.go:149: staring export to: <zip archive: /Users/rustam/wp/test3.zip>
> <...>
> 2022/07/23 10:35:02 downloader.go:285: wait complete:  all files downloaded
> 2022/07/23 10:35:02 export.go:301: downloader stopped
> 2022/07/23 10:35:02 app.go:143: closing file system
> 2022/07/23 10:35:02 app.go:72: completed, time taken: 17m53.362280238s
> ```
> 
> Archive test:
> 
> ```
> $ ls -l ~/wp/test3.zip
> 2.3G 23 Jul 10:35 /Users/rustam/wp/test3.zip
> 
> $ unzip -t ~/wp/test3.zip
> <... lots of text ...>
> No errors detected in compressed data of /Users/rustam/wp/test3.zip.
> 
> $ 7z t ~/wp/test3.zip    
> 
> 7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
> p7zip Version 17.04 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,16 CPUs x64)
> 
> Scanning the drive for archives:
> 1 file, 2425607730 bytes (2314 MiB)
> 
> Testing archive: /Users/rustam/wp/test3.zip
> --
> Path = /Users/rustam/wp/test3.zip
> Type = zip
> Physical Size = 2425607730
> 
> Everything is Ok                                                               
> 
> Files: 3897
> Size:       2515025147
> Compressed: 2425607730
> ```
> 
> Unpack test on windows finished with no errors, it complained about some unusual file names of the attachments, i.e. emojis in filenames, but otherwise everything unpacked.:
> 
> <img alt="image" width="640" src="https://user-images.githubusercontent.com/16064414/180585828-68830dff-7794-42ab-a899-4ee5a08dd9dd.png">
> 
> Could you try this one please and let me know if that fixes the issue for you?

Hi @rusq , Thanks for checking this.
I can confirm that this has taken care of the problem and I can get the export done without issue and view the export without any issue.

Thanks again
