### ISSUE TITLE
Internal Server Error when exporting a very large thread (800+ messages)

### ISSUE THREAD

**Issue by pican79** [rusq/slackdump#54] opened 2022-05-05 12:08 UTC
**Describe the bug**
I'm trying to export a thread with more than 800 messages (as of today) but I get an error when I run the following command:
`./slackdump -r text https://xyz.slack.com/archives/RK9N4AFRB/p165158407`

This thread mostly contains images, some text messages, some links, standard/custom emojis/reactions.

I can export smaller threads (fewer than 5 messages) that are either older or newer from the same private channel without any problem.

I'm using version 1.3.5.

**Output**
```
2022/05/05 13:31:54 > checking user cache...
2022/05/05 13:32:07 error processing: "https://xyz.slack.com/archives/RK9N4AFRB/p165158407" (conversation will be skipped): slack server error: 500 Internal Server Error
2022/05/05 13:32:07 job finished, dumped 0 item(s)
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by rusq** [comment] 2022-05-06 03:13
Hey @pican79, do you mind rerunning it with `-trace=trace.out` flag, i.e.:
```shell
C:\> slackdump.exe -trace=trace.out https://xyz.slack.com/archives/RK9N4AFRB/p165158407
```
and then upload the `trace.out` to https://www.dropbox.com/request/eEK5YK1srbvXPyBmnvys ?

It is a curious case, because there's no technical difference between downloading a thread with 5 messages or with 800.

**Comment by rusq** [comment] 2022-05-06 23:30
No, credentials are blanked before writing the current config.  Trace.out is a binary file I'm not sure that you can easily edit it without breaking the structure.  The Dropbox link is private, and only I have access to the directory.  I'm not using the information from the trace files for anything else but trying to understand the issue.

You can run "go tool trace trace.out" on that file and see for yourself what data it contains and whether you're comfortable sharing it. (You'll need to install golang on your machine)

**Comment by rusq** [comment] 2022-05-07 00:05
This is the corresponding code for v1.3.5 that blanks the creds: https://github.com/rusq/slackdump/blob/v1.3.5/cmd/slackdump/main.go#L106-L107

**Comment by rusq** [comment] 2022-05-07 04:18
I've been experimenting on my test Slack instance, and wasn't able to reproduce the error:
```
2022/05/07 14:14:35 enabling trace, will write to "trace.out"
2022/05/07 14:14:35 > checking user cache...
2022/05/07 14:14:36   thread request #    1, fetched:  801, total:      801, process results:  (speed: 1184.75/sec, avg: 1184.75/sec)
2022/05/07 14:14:36   thread fetch complete, total: 801
2022/05/07 14:14:36 generating CHYLGDP0D-1651896041.895139.json
2022/05/07 14:14:36 dumped 1 item(s)
2022/05/07 14:14:36 completed, time taken: 953.33479ms
```

```
[2:14:36] 0:github.com/rusq/slackdump (ez-login)> cat CHYLGDP0D-1651896041.895139.json|wc -l
   32843
```

My steps were:
1. Generate a thread with 800 messages;
2. Dump the thread.

You can also try the version v2.0.0-alpha, i doubt that it will resolve the 500 internal error as it is a server-side error.  Let me know.

**Comment by rusq** [comment] 2022-05-07 04:23
Also, can you confirm that this is, aside, from the slack workspace name, a URL that you've been using to start slackdump? 
```
https://xyz.slack.com/archives/RK9N4AFRB/p165158407
```

The value `p165158407` is not a valid slack thread timestamp (it resolves to `Thu Mar 27 23:20:07 1975` which is not possible)

**Comment by pican79** [comment] 2022-05-07 13:29
You're right, the thread url timestamp I used in the bug description doesn't match anything I have in my command history.
Must've been a copy/paste error.

After modifying the url's human-readable characters in the trace.out file with a regular text editor, it was no longer usable with "go tool trace".

So I edited the hexa with vim (that was super fun).
The resulting file (20220507-1.out) still works with "go tool trace" and displays `https://abc-defgh.slack.com/...` instead of the original url in the "user-defined tasks" page.

I zipped it and uploaded the zip file (called trace_issue54_pican79.zip) in your Dropbox folder.

Let me know if you have any issue analyzing it.

When I have more time, I'll test the v2.0.0-alpha version.
Thanks.

**Comment by rusq** [comment] 2022-05-07 22:19
Thanks @pican79 , the trace helped.

I noticed that `GetConversationRepliesContext` call "hangs in there" for 10 seconds (±0.3 sec) , before the server returns 500 Internal Server Error.  On my test environment this operation takes around 0.5 sec, it seems that thread you're trying to fetch is not only long, it's also fat.

I couldn't help myself but to go read the API docs again and noticed that the default batch size (`Limit` parameter) for this API call is 1'000 messages, meaning that with each API call it will get at most 1'000 messages.

My uneducated guess would be - there's a server-side timeout for the operation, and that timeout is 10 seconds.  Once the caller (slackdump in this case) hits that timeout, the server says "meh" and returns 500 error.

I'm going to add another configuration parameter, that allows to set this Limit to an arbitrary value, and then, most likely, by reducing this parameter's value, it will work.

**Comment by rusq** [comment] 2022-05-07 23:15
I have built a v2.beta.2 which has the `-rpr` parameter, that allows to specify the "replies per request" value, it defaults to `200` messages per request (slack api default is 1000).

So, if the default doesn't work (if you still getting 500 Error), try decreasing it, i.e
```shell
slackdump.exe -rpr=100 <url>
```
Could you please try and see if helps to fix the issue?

Also, would be interesting to see what would be the MAX value of this parameter that would work for you?

https://github.com/rusq/slackdump/releases/download/v2.0.0-beta.2/slackdump-v2.0.0-beta.2-windows-amd64.zip

**Comment by pican79** [comment] 2022-05-08 18:45
Thank you very much, @rusq,  for the new version.

Using v2.0.0-beta.2, I was able to export the thread with 800+ messages successfully.
I didn't need to modify the default value for the new `rpr` parameter.

I also tried with the `-f` parameter.
It successfully exported the 500+ image files (weighing ~65Mb in total).

Would my slow internet connection explain why I encountered the "500 error" with v1.3.5?

**Comment by rusq** [comment] 2022-05-08 23:11
I can only guess, but my guess is that there's something like golangs "context timeout" on that handler, once the request comes, it records the start time, then queries the database, if the database operation exceeds this timeout, the database operation terminates, and the handler returns 500 Internal Server Error.  I don't think it's related to the slow internet connection.

I'm glad that it's resolved for you, and also - thank you for your help in resolving this (what seemed like "it's their problem") issue :)

I'm going to close it.

**Closed by rusq** 2022-05-08 23:11 UTC
